// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldMonitor.Data;

#nullable disable

namespace WorldMonitor.Data.Migrations
{
    [DbContext(typeof(WorldMonitorDbContext))]
    [Migration("20260617032403_AddWaitlistAccess")]
    partial class AddWaitlistAccess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorldMonitor.Data.Entities.Access.UserApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("UX_UserApiKeys_KeyHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserApiKeys_User");

                    b.ToTable("UserApiKeys", (string)null);
                });

            modelBuilder.Entity("WorldMonitor.Data.Entities.CacheEntry", b =>
                {
                    b.Property<string>("CacheKey")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("ByteLength")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("CAST(DATALENGTH([Value]) AS bigint)", true);

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxContentAgeMin")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NewestItemAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecordCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("State")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CacheKey");

                    b.HasIndex("FetchedAt")
                        .HasDatabaseName("IX_CacheEntries_FetchedAt");

                    b.ToTable("CacheEntries", (string)null);
                });

            modelBuilder.Entity("WorldMonitor.Data.Entities.Identity.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocalePrimary")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("LocaleTag")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Timezone")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("UserId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("IX_Users_NormalizedEmail");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WorldMonitor.Data.Entities.Identity.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Variant")
                        .IsUnique()
                        .HasDatabaseName("UX_UserPreferences_User_Variant");

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("WorldMonitor.Data.Entities.Notifications.AlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AiDigestEnabled")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("Channels")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Countries")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DigestHour")
                        .HasColumnType("int");

                    b.Property<string>("DigestMode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("DigestTimezone")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("EventTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("QuietHoursEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("QuietHoursEnd")
                        .HasColumnType("int");

                    b.Property<string>("QuietHoursOverride")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("QuietHoursStart")
                        .HasColumnType("int");

                    b.Property<string>("QuietHoursTimezone")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("IX_AlertRules_Enabled");

                    b.HasIndex("UserId", "Variant")
                        .IsUnique()
                        .HasDatabaseName("UX_AlertRules_User_Variant");

                    b.ToTable("AlertRules", (string)null);
                });

            modelBuilder.Entity("WorldMonitor.Data.Entities.Notifications.NotificationChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ChannelType")
                        .IsUnique()
                        .HasDatabaseName("UX_NotificationChannels_User_Channel");

                    b.ToTable("NotificationChannels", (string)null);

                    b.HasDiscriminator<string>("ChannelType").HasValue("NotificationChannel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WorldMonitor.Data.Entities.Notifications.TelegramPairingToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Variant")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("UX_TelegramPairingTokens_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_TelegramPairingTokens_User");

                    b.ToTable("TelegramPairingTokens", (string)null);
                });

            modelBuilder.Entity("WorldMonitor.Data.Entities.Waitlist.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Organization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail", "ReceivedAt")
                        .HasDatabaseName("IX_ContactMessages_Email_Received");

                    b.ToTable("ContactMessages", (string)null);
                });

            modelBuilder.Entity("WorldMonitor.Data.Entities.Waitlist.EmailSuppression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("SuppressedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_EmailSuppressions_NormalizedEmail");

                    b.ToTable("EmailSuppressions", (string)null);
                });

            modelBuilder.Entity("WorldMonitor.Data.Entities.Waitlist.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppVersion")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ReferralCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("ReferralCount")
                        .HasColumnType("int");

                    b.Property<string>("ReferredBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_Registrations_NormalizedEmail");

                    b.HasIndex("ReferralCode")
                        .HasDatabaseName("IX_Registrations_ReferralCode");

                    b.ToTable("Registrations", (string)null);
                });

            modelBuilder.Entity("WorldMonitor.Data.Entities.Waitlist.UserReferralCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_UserReferralCodes_Code");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_UserReferralCodes_User");

                    b.ToTable("UserReferralCodes", (string)null);
                });

            modelBuilder.Entity("WorldMonitor.Data.Entities.Waitlist.UserReferralCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefereeEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ReferrerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ReferrerUserId", "RefereeEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_UserReferralCredits_Referrer_Email");

                    b.ToTable("UserReferralCredits", (string)null);
                });

            modelBuilder.Entity("WorldMonitor.Data.Entities.Watchlist.FollowedCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Country")
                        .HasDatabaseName("IX_FollowedCountries_Country");

                    b.HasIndex("UserId", "Country")
                        .IsUnique()
                        .HasDatabaseName("UX_FollowedCountries_User_Country");

                    b.ToTable("FollowedCountries", (string)null);
                });

            modelBuilder.Entity("WorldMonitor.Data.Entities.Notifications.DiscordChannel", b =>
                {
                    b.HasBaseType("WorldMonitor.Data.Entities.Notifications.NotificationChannel");

                    b.Property<string>("DiscordChannelId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscordGuildId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebhookEnvelope")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WebhookEnvelope");

                    b.HasDiscriminator().HasValue("discord");
                });

            modelBuilder.Entity("WorldMonitor.Data.Entities.Notifications.EmailChannel", b =>
                {
                    b.HasBaseType("WorldMonitor.Data.Entities.Notifications.NotificationChannel");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("email");
                });

            modelBuilder.Entity("WorldMonitor.Data.Entities.Notifications.SlackChannel", b =>
                {
                    b.HasBaseType("WorldMonitor.Data.Entities.Notifications.NotificationChannel");

                    b.Property<string>("SlackChannelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlackConfigurationUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlackTeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebhookEnvelope")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WebhookEnvelope");

                    b.HasDiscriminator().HasValue("slack");
                });

            modelBuilder.Entity("WorldMonitor.Data.Entities.Notifications.TelegramChannel", b =>
                {
                    b.HasBaseType("WorldMonitor.Data.Entities.Notifications.NotificationChannel");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("telegram");
                });

            modelBuilder.Entity("WorldMonitor.Data.Entities.Notifications.WebPushChannel", b =>
                {
                    b.HasBaseType("WorldMonitor.Data.Entities.Notifications.NotificationChannel");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("UX_NotificationChannels_Endpoint")
                        .HasFilter("[Endpoint] IS NOT NULL");

                    b.HasDiscriminator().HasValue("web_push");
                });

            modelBuilder.Entity("WorldMonitor.Data.Entities.Notifications.WebhookChannel", b =>
                {
                    b.HasBaseType("WorldMonitor.Data.Entities.Notifications.NotificationChannel");

                    b.Property<string>("WebhookEnvelope")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WebhookEnvelope");

                    b.Property<string>("WebhookLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebhookSecret")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("webhook");
                });
#pragma warning restore 612, 618
        }
    }
}
