// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldMonitor.Data;

#nullable disable

namespace WorldMonitor.Data.Migrations
{
    [DbContext(typeof(WorldMonitorDbContext))]
    partial class WorldMonitorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorldMonitor.Data.Entities.CacheEntry", b =>
                {
                    b.Property<string>("CacheKey")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<long>("ByteLength")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasComputedColumnSql("CAST(DATALENGTH([Value]) AS bigint)", true);

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxContentAgeMin")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NewestItemAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecordCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("State")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CacheKey");

                    b.HasIndex("FetchedAt")
                        .HasDatabaseName("IX_CacheEntries_FetchedAt");

                    b.ToTable("CacheEntries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
